### ISSUE TITLE
macro 'dbt_macro__ref' takes no keyword argument 'v'

### ISSUE THREAD

**Issue by andreviniciusmb** [LewisDavies/upstream-prod#11]
## Describe the feature
With the update of dbt versions, we now have the possibility to add the version in the `ref.sql` file, as referenced [here](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#versioned-ref). When using the dbt Python Models and the upstream-prod I had a problem because the dbt does not find the argument `'v'` which would be the version of the macro ref, as shown in the image below:

<img src="https://github.com/LewisDavies/upstream-prod/assets/44850779/03845096-9ced-4bee-b911-7babe00943d7" width=600 height=200 />

## Possible Solution

Add the arguments 'v' or 'version' to the ref macro.

## Environment
```yml
- OS: Linux 22.04.2 LTS
- Python: 3.9.16
- dbt: 1.5.1
- upstream_prod: 0.5.0
 ```
