### ISSUE TITLE
`ref()` returns `None` when prod table doesn't exist even if `upstream_prod_fallack: True`

### ISSUE THREAD

**Issue by garfieldthesam** [LewisDavies/upstream-prod#4]
This might be a misunderstanding of how the package works so please let me know if this is just an unsupported feature. 

Using `dbt-bigquery` I have a config like this in my `profiles.yml` for `upstream_prod`:

```
vars:
  # upstream-prod config
  upstream_prod_schema: prod_schema_prefix
  upstream_prod_enabled: True
  upstream_prod_fallack: True
```

Where `prod_schema_prefix` matches the prefix applied to the many prod schemas in our data warehouse (eg. there's my personal dev schemas like `dbt_myname_staging` and prod schemas like `prod_schema_prefix_staging`).

I have created a new table `tbl1` and updated `tbl2` to query from `tbl1` like `from {{ ref("tbl1") }}`. When this compiles with `upstream_prod_enabled: True`, it compiles as `from None`.
